In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.expand_frame_repr', True)

In [59]:
data = np.genfromtxt('day8_input.txt', delimiter=1, dtype=int)
print(data)

[[0 0 0 ... 2 1 2]
 [0 2 0 ... 2 1 0]
 [0 1 2 ... 1 2 2]
 ...
 [2 2 1 ... 1 2 1]
 [2 1 1 ... 0 2 2]
 [2 0 2 ... 2 2 1]]


# Part 1

In [60]:
len(data)

99

In [61]:
def check_if_edge(x, y, data):
    size = len(data)-1
    check_valid = data[x, y]
    if x == 0 or y == 0 or x == size or y == size:
        return True
    else:
        return False
    

In [62]:
check_if_edge(1, 4, data)

False

In [35]:
def check_if_visible(x, y, data):
    tree = data[x, y]
    up = max(data[:x, y])
    down = max(data[x+1:, y])
    left = max(data[x, :y])
    right = max(data[x, y+1:])
    
    #print(tree, up, down, left, right)
    if tree > up or tree > down or tree > right or tree > left:
        #print("row", data[x, :], "column", data[:,y])
        return True
    
    else:
        return False
    

In [63]:
count_visible_edge = 0
count_visible_inside = 0
for x in range(0, len(data)):
    for y in range(0, len(data)):
        if check_if_edge(x, y, data):
            #print(True)
            count_visible_edge+=1
        else:
            #print(check_if_visible(x, y, data))
            if check_if_visible(x, y, data):
                #print("coord", x, y, "True value", data[x,y])
                count_visible_inside+=1
#            else:
#                print("coord", x, y, "False value", data[x,y])


print(count_visible_inside, count_visible_edge, count_visible_inside+count_visible_edge)            
        

1387 392 1779


# Part 2

In [64]:
def check_distance_dir(start, direc, sign):
    counter_dist = 0
    for n in direc[::sign]:
        if n < start:
            counter_dist +=1
        if n>= start:
            counter_dist += 1
            break
    return counter_dist
    

In [65]:
def check_scenic_score(x, y, data):
    tree = data[x, y]
    up = data[:x, y]
    down = data[x+1:, y]
    left = data[x, :y]
    right = data[x, y+1:]
    
    score_up = check_distance_dir(tree, up, -1)
    score_down = check_distance_dir(tree, down, 1)
    score_left = check_distance_dir(tree, left, -1)
    score_right = check_distance_dir(tree, right, 1)
    scenic_score = score_up * score_down * score_left * score_right
    
    return scenic_score


In [69]:
max_scenic_score = 0
for x in range(0, len(data)):
    for y in range(0, len(data)):
        score =  check_scenic_score(x, y, data)
        if score >= max_scenic_score:
            max_scenic_score = score
            
print(max_scenic_score)

172224
